project:
  output-dir: _slides
  render:
    - lectures_intro.qmd
    - week01.qmd
    - data_representation.qmd
    - week02.qmd

title: "EG-151 Microcontrollers"
author: "Chris Jobling"
date: "27/08/2024"
bibliography: references.bib

format: revealjs

