---
author: 
  name: "Dr Timothy Davies"
  affiliation: "Department of Electronic and Electrical Engineering"
date: "9/30/2025"
number-sections: false
---

# Assessment of the Laboratory Introduction {#sec-labintro-assessment}

**Start date**: Tuesday, 30th September 2025

The laboratory introduction is assessed according to the following:

-   Health and safety and safe in the electronics laboratory.
-   Breadboard construction exercise.
-   Testing of the circuit using a plug-in breadboard and National
    Instruments Multisim.
-   Answers to questions at the end of the laboratory introduction
    script marked automatically by means of a Canvas quiz.
-   Construction of a Tic-Tac box continuity tester.

Marking is done and feedback is given jointly by the module coordinator
and the chief Electronics technician.

**Submission components**:

-   Lab diary with record of breadboard construction exercise and
    simulation (5 marks with formative feedback on diary entry)
-   Answers to questions - Canvas Quiz (5 marks)
-   Inspection of Tic-Tac box continuity tester (5 marks)

**Deadline for submission**: 16:00 25th October 2024
**Deadline for feedback**: 15th November 2024 or fifteen working days
after submission.
