project:
  type: book
  output-dir: _build/html

book:
  cover-image: cover.jpg
  cover-image-alt: An Intel 8742 Microprocessor
  repo-url: https://github.com/cpjobling/eg-151-textbook
  repo-actions: [edit, issue]
  repo-branch: quarto-version
  repo-subdir: eg-151-textbook
  site-url: https://cpjobling.github.io/eg-151-textbook
  favicon: logo.png
  title: "EG-151 Microcontrollers 2024-2025"
  author:
    - "Chris Jobling"
    - "Hayder Jahanger"
    - "Timothy Davies"
    - "Ben Clifford"
  publisher: Department of Electronic and Electrical Engineering, School of Aerospace, Civil, Electrical, General and Mechanical Engineering (SACEGME), Faculty of Science and Engineering, Swansea University
  publisher-place: Swansea, UK
  date: 08/23/2024
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
  chapters:
    - index.qmd
    - part: "Course Introduction"
      chapters:
       - intro_course_aims.qmd
       - intro_course_delivery.qmd
    - part: lectures.qmd
      chapters: 
        - lectures_intro.qmd
        - week01.qmd
        - data_representation.qmd
        - week02.qmd
    - references.qmd

bibliography: references.bib

highlight-style: pygments

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
  pdf:
    documentclass: scrreprt

# root: intro
# parts:
#   - caption: Course Introduction
#     chapters:
#      - file: intro/course_aims
#      - file: intro/course_delivery
#   - caption: Introduction to Microcontrollers
#     chapters:
#     - file: lectures/index
#     - file: lectures/intro
#     - file: lectures/week01/index
#     - file: lectures/data_representation/index
#     - file: lectures/week02/index
#     - file: lectures/week03/index
#     - file: lectures/week04/index
#     - file: lectures/week05/index
#     - file: lectures/week06/index
#     - file: lectures/week07/index
#     - file: lectures/week08/index
#     - file: lectures/week09/index
#     - file: references
#   - caption: Programming in C
#     numbered: false
#     chapters:
#     - file: programming_in_c/index
#     - file: programming_in_c/the_task
#     - file: programming_in_c/understanding_the_task
#     - file: programming_in_c/wiring_the_circuit
#     - file: programming_in_c/using_the_ide
#     - file: programming_in_c/setting_up_the_io
#     - file: programming_in_c/detecting_and_reacting_to_a_button_press
#   - caption: Laboratory Introduction
#     numbered: false
#     chapters:
#     - file: lab_intro/intro
#     - file: lab_intro/assessment
#     - file: lab_intro/lab_work
#     - file: lab_intro/lab_instruments
#     - file: lab_intro/lab_safety
#     - file: lab_intro/experiment0
#     - file: lab_intro/simulation
#     - file: lab_intro/questions
#     - file: lab_intro/construction
#     - file: lab_intro/soldering
#   - caption: Laboratory Experiments
#     chapters:
#     - file: labs/index 
#     - file: labs/get_started/index
#     - file: labs/lab01/index
#     - file: labs/lab02/index
#     - file: labs/lab03/index
#     - file: labs/lab04/index
#     - file: labs/lab05/index
#   - caption: Mini Projects
#     chapters:
#     - file: projects/index
#     - file: projects/voltmeter
#     - file: projects/bipolar_voltage_measurement
#     - file: projects/range_finder
#     - file: projects/clock_timer
#     - file: projects/weather_station
#   - caption: Appendices
#     chapters:
#     - file: appendix/appendix_a
#       sections: 
#       - file: appendix/2scomp
#       - file: appendix/bcd
#       - file: appendix/binary_fractions
#       - file: appendix/ascii
